version: 0.2
phases:
  pre_build:
    commands:
      chmod +x grailsw
  build:
    commands:
      ./grailsw clean && ./grailsw war
      touch build/libs/dummy.war

artifacts:
  type: zip
  files:
    - build/libs/*.war
  discard-paths: yes